apiVersion: v1
kind: Pod
metadata:
  name: nginx-swarmtest
  labels:
    app: myapp
spec:
  containers:
  - name: s1
    image: ichte/swarmtest:node
    resources:
     limits:
       memory: "150Mi"
       cpu: "100m"
    ports:
      - containerPort: 8085